"""Run the ablation study and write the results for the report.

    python tests/opt_ablation_run.py --executor reference
    python tests/opt_ablation_run.py --executor codegen --scale 1 --repeat 5
    python tests/opt_ablation_run.py --order

Executors:
  reference  the tests' reference evaluator, on the suite's own tables. It is a
             naive row-at-a-time interpreter with nested-loop joins, so it
             exaggerates join costs; it runs anywhere.
  codegen    Person C's generated code (codegen.generate + compile_and_run) on
             the larger tables of opt_bench_data.py. Needs Person C's code.

Writes docs/ablation/<executor>.csv (one row per query and configuration, for
Person A's charts) and docs/ablation/<executor>.md (the summary), or with
--order, docs/ablation/pass_order.md.
"""

from __future__ import annotations

import argparse
import platform
import subprocess
import sys
from pathlib import Path

sys.path[:0] = [str(Path(__file__).parent), str(Path(__file__).parent.parent)]

import opt_ir  # noqa: E402,F401
import opt_query_suite as S  # noqa: E402

import optimizer  # noqa: E402
from optimizer.ablation import (  # noqa: E402
    cost_model_check, order_table, pass_order_study, per_query_table, run_ablation, summary_table, to_csv,
)

OUT = Path(__file__).parent.parent / "docs" / "ablation"


def reference_executor():
    from opt_reference_eval import evaluate

    def prepare(plan):
        return lambda: evaluate(plan, S.TABLES).rows

    return prepare, S.CATALOG, None, "the suite's own tables (3 to 80 rows)"


def codegen_executor(scale: int):
    from codegen import generate
    from codegen.runner import compile_module
    from runtime import Table, compare_tables

    import opt_bench_data as B

    tables = B.make_tables(scale)
    catalog = B.catalog(tables)
    runtime_tables = {
        name: Table.from_rows([(c, t, name) for c, t in S.SCHEMAS[name]], rows)
        for name, (_, rows) in tables.items()
    }

    def prepare(plan):
        run = compile_module(generate(plan, catalog, mode="compiled"))["run"]
        return lambda: run(runtime_tables)

    def same(a, b):
        return compare_tables(b, a)[0]

    sizes = ", ".join(f"{t} {len(rows):,}" for t, (_, rows) in tables.items() if not t.startswith("k"))
    return prepare, catalog, same, f"opt_bench_data.py at scale {scale}: {sizes}, k1..k9 {len(tables['k1'][1]):,} each"


def _without_outlier(measurements) -> list[str]:
    """The totals again, without the query that contributes most to the unoptimized total."""
    slowest = max((m for m in measurements if m.config == "no passes"), key=lambda m: m.runtime_ms)
    total = sum(m.runtime_ms for m in measurements if m.config == "no passes")
    share = slowest.runtime_ms / total if total else 0
    rest = [m for m in measurements if m.query != slowest.query]
    return [
        f"One query, `{slowest.query}`, takes {share:.0%} of the unoptimized total. "
        "The same totals without it:",
        "",
        summary_table(rest),
        "",
    ]


def _git(*args) -> str:
    try:
        return subprocess.run(["git", *args], capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def run(executor: str, scale: int, repeat: int, note: str) -> None:
    if executor == "reference":
        prepare, catalog, same, data = reference_executor()
    else:
        prepare, catalog, same, data = codegen_executor(scale)
    queries = [(q.name, q.plan) for q in S.QUERIES]
    measurements = run_ablation(queries, catalog, prepare, repeat=repeat, same=same)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{executor}.csv").write_text(to_csv(measurements))
    passes = [p.name for p in optimizer.default_passes()]
    lines = [
        f"# Ablation: {executor} executor",
        "",
        "Generated by `python tests/opt_ablation_run.py "
        + (f"--executor codegen --scale {scale}" if executor == "codegen" else "--executor reference")
        + f" --repeat {repeat}`. The raw numbers are in `{executor}.csv`.",
        "",
        f"* Queries: the {len(queries)} queries of the optimizer's differential suite.",
        f"* Data: {data}.",
        f"* Runtime: the fastest of {repeat} runs of each plan, excluding optimization"
        + (", code generation and compilation." if executor == "codegen" else "."),
        f"* Code: {note}." if note else f"* Code: commit `{_git('rev-parse', '--short', 'HEAD')}`.",
        f"* Machine: {platform.processor() or platform.machine()}, Python {platform.python_version()}.",
        "",
        "## Totals over all queries",
        "",
        summary_table(measurements),
        "",
        "`wrong results` counts queries whose result differs from the plan as written. It must be 0.",
        "",
        *_without_outlier(measurements),
        "## Does the cost model predict the runtimes?",
        "",
        cost_model_check(measurements),
        "",
        "## Where each pass matters most",
        "",
    ]
    for p in passes:
        lines += [f"### Without {p}", "", per_query_table(measurements, "all passes", f"without {p}", top=5), ""]
    lines += ["### No passes at all", "", per_query_table(measurements, "all passes", "no passes", top=8), ""]
    (OUT / f"{executor}.md").write_text("\n".join(lines))
    print(summary_table(measurements))
    print(f"wrote {OUT / executor}.csv and .md")


def order() -> None:
    queries = [(q.name, q.plan) for q in S.QUERIES]
    results = pass_order_study(queries, S.CATALOG)
    lines = [
        "# Pass order study",
        "",
        "Generated by `python tests/opt_ablation_run.py --order`.",
        "",
        f"Every order of the four passes, each run to a fixed point on the {len(queries)} suite queries.",
        "The cost is the B5 cost model's estimate for the final plans, summed. Pass applications and",
        "iterations count the work the fixed-point loop did to get there.",
        "",
        order_table(results),
        "",
    ]
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "pass_order.md").write_text("\n".join(lines))
    print(order_table(results))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--executor", choices=["reference", "codegen"])
    parser.add_argument("--scale", type=int, default=1)
    parser.add_argument("--repeat", type=int, default=5)
    parser.add_argument("--note", default="", help="extra provenance, e.g. which codegen commit")
    parser.add_argument("--order", action="store_true", help="run the pass order study")
    args = parser.parse_args()
    if args.order:
        order()
    if args.executor:
        run(args.executor, args.scale, args.repeat, args.note)


if __name__ == "__main__":
    main()
