"""Regenerate docs/cardinality_estimates.md: ``python tests/opt_cardinality_table.py``.

Runs the validation harness (optimizer/cardinality_report.py) over the
estimator workload and the differential suite. Actual row counts come from
the reference evaluator, one subtree at a time.
"""

from __future__ import annotations

import sys
import warnings
from pathlib import Path

sys.path[:0] = [str(Path(__file__).parent), str(Path(__file__).parent.parent)]

import opt_ir  # noqa: E402,F401
import opt_query_suite as S  # noqa: E402
import opt_stats_workload as W  # noqa: E402
from opt_reference_eval import evaluate  # noqa: E402

import optimizer  # noqa: E402
from optimizer.cardinality_report import cell, compare, detail_table, summarize, summary_table  # noqa: E402

OUT = Path(__file__).parent.parent / "docs" / "cardinality_estimates.md"


# Why each suite query that can appear among the worst estimates is off. The
# report refuses to list a worst case nobody has explained.
CAUSES = {
    "having_on_aggregate": "the HAVING predicate reads a SUM, which has no statistics, so it gets System R's 1/3.",
    "having_splits_on_group_key": "the HAVING predicate reads a SUM, which has no statistics, so it gets "
                                  "System R's 1/3.",
    "left_join_is_null_must_not_push": "it counts customers with no orders, which containment says do not "
                                       "exist: `orders.o_custkey` and `customer.c_id` have the same number "
                                       "of distinct values, but not the same values.",
    "five_way_join_in_a_bad_order": "four joins, each a little off, and the errors multiply.",
    "forced_cross_product": "a cross product multiplies the errors of its inputs: two of the five nations "
                            "are in AMERICA (1.25 expected), and three employees work in a department with "
                            "a budget over 500 (2.1 expected).",
    "filter_through_project_over_join": "containment again: `orders.o_custkey` includes the keys 13 and 14, "
                                        "which no customer has.",
    "filter_through_three_way_join": "two of the five nations are in AMERICA, against 1.25 expected.",
    "three_relation_conjunct": "the comparison across three tables has no statistics, so it gets "
                               "System R's 1/3.",
    "nine_way_chain": "eight joins over 6-row tables whose keys are random rather than uniform.",
}


def _cause(query: str) -> str:
    if query not in CAUSES:
        raise KeyError(f"{query} is among the worst estimates: add the reason to CAUSES")
    return CAUSES[query]


def counter(tables):
    return lambda node: len(evaluate(node, tables).rows)


def workload_rows():
    return {q.name: compare(q.name, q.plan, W.CATALOG, counter(W.TABLES)) for q in W.QUERIES}


def suite_rows(optimized: bool):
    out = []
    for q in S.QUERIES:
        plan = q.plan
        if optimized:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                plan, _ = optimizer.optimize(plan, S.CATALOG)
        out += compare(q.name, plan, S.CATALOG, counter(S.TABLES))
    return out


def render() -> str:
    work = workload_rows()
    roots = {name: rows[0] for name, rows in work.items()}
    held = [roots[q.name] for q in W.QUERIES if q.assumption_holds]
    broke = [roots[q.name] for q in W.QUERIES if not q.assumption_holds]
    held_s, broke_s = summarize(held, by_kind=False)[0], summarize(broke, by_kind=False)[0]
    worst_held, *rest_held = sorted(held, key=lambda r: -r.q_error)
    optimized, original = suite_rows(True), suite_rows(False)
    opt_all = summarize(optimized, by_kind=False)[0]
    worst = sorted(optimized, key=lambda r: -r.q_error)[:10]
    q = {name: r.q_error for name, r in roots.items()}

    lines = [
        "# Cardinality estimates vs actual row counts",
        "",
        "Generated by `python tests/opt_cardinality_table.py`; do not edit by hand.",
        "The estimator is `optimizer/stats.py`; the harness is `optimizer/cardinality_report.py`.",
        "",
        "Every number compares the estimator's row count for a plan node with the row count the",
        "reference evaluator returns for that node's subtree. The error measure is the **q-error**,",
        "max(estimate / actual, actual / estimate) with both counts raised to at least 1 row:",
        "1.00 is exact, and 2.00 means off by a factor of two in either direction.",
        "",
        "## 1. Where the estimator is right, and where it is wrong",
        "",
        "`tests/opt_stats_workload.py` has 1,000 events, 100 users and 300 clicks. Each column was",
        "generated to meet or to break one assumption of the estimator, and each query tests one rule.",
        "The table shows each query's root node.",
        "",
        "| query | what it tests | data meets the assumption? | estimated | actual | q-error |",
        "|---|---|---|--:|--:|--:|",
    ]
    for wq in W.QUERIES:
        r = roots[wq.name]
        lines.append(f"| {wq.name} | {cell(wq.tests)} | {'yes' if wq.assumption_holds else '**no**'} "
                     f"| {r.estimated:.1f} | {r.actual} | {r.q_error:.2f} |")
    lines += [
        "",
        f"Where the data meets the estimator's assumptions ({held_s.nodes} queries), the median q-error is "
        f"{held_s.median:.2f} and the worst is {held_s.worst:.2f}: {worst_held.query} estimates "
        f"{worst_held.estimated:.0f} rows against {worst_held.actual}, which is sampling noise. "
        f"Where the data breaks an assumption "
        f"({broke_s.nodes} queries), the median is {broke_s.median:.2f} and the worst {broke_s.worst:.2f}.",
        "The failures are systematic, and each has a known cause:",
        "",
        f"* **Skew** (`z` is Zipf-distributed). Equality assumes every value is equally common, so it "
        f"under-estimates the most frequent value by {q['skewed_equality_frequent']:.1f}x and over-estimates "
        f"the rarest by {q['skewed_equality_rare']:.1f}x. A join on skewed keys on both sides is "
        f"{q['skewed_join']:.1f}x too low, because the frequent values meet each other far more often than "
        "uniformity predicts. The fix is a most-common-values list or a histogram in the catalog; Contract §6 "
        "provides neither, so it would be a request to Person A.",
        f"* **Correlation** (`b` always equals `a`). AND multiplies selectivities, so `a = 7 AND b = 7` is "
        f"{q['correlated_and']:.1f}x too low, and GROUP BY a, b multiplies distinct counts, which is "
        f"{q['group_by_correlated']:.1f}x too high. Fixing this needs multi-column statistics.",
        f"* **No statistics to use.** A range on a string column can't be interpolated, and a HAVING "
        f"predicate reads an aggregate the catalog knows nothing about; both fall back to System R's 1/3 "
        f"(q-errors {q['string_range']:.2f} and {q['having']:.2f}).",
        "",
        "Every other query whose data meets the assumptions (foreign-key and filtered-dimension joins,",
        "LEFT joins, IS NULL, OR, NOT, date ranges, two-sided ranges, grouped aggregates over a filter)",
        f"is within {rest_held[0].q_error:.2f}x.",
        "",
        "## 2. Every node of the differential suite, after optimization",
        "",
        "These are the plans the cost model ranks during join reordering. The suite's tables have 3 to 60",
        "rows, so a difference of a few rows shows up as a large ratio: an estimate of 1 row against an",
        "actual 3 is a q-error of 3.",
        "",
        summary_table(optimized),
        "",
        f"{opt_all.within_2x:.0%} of the {opt_all.nodes} nodes are within 2x. The worst ten:",
        "",
        detail_table(worst, indent=False),
        "",
        f"Every node in that list returns {max(r.actual for r in worst)} rows or fewer. Why each query is off:",
        "",
        *[f"* `{name}`: {_cause(name)}" for name in dict.fromkeys(r.query for r in worst)],
        "",
        "<details><summary>Every node of every query</summary>",
        "",
        detail_table(optimized),
        "",
        "</details>",
        "",
        "## 3. The same queries before optimization",
        "",
        summary_table(original),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
