"""Phase C2: emitter, generate() module shape, runner error reporting, passthrough parity."""
import ast

import pytest

from codegen import Emitter, GeneratedCodeError, compile_and_run, generate
from runtime import compare_tables, interpret
from runtime._compat import DType

from codegen_fixtures import CATALOG, SAMPLE_PLANS, TABLES, col, lit, op, scan

SAMPLE_IDS = sorted(SAMPLE_PLANS)


# ------------------------------------------------------------------ Emitter

def test_emitter_indentation_blocks_and_imports():
    em = Emitter()
    em.import_("import numpy as np")
    em.import_("import numpy as np")  # de-duplicated
    with em.block("def run(tables):"):
        with em.block("for i in range(3):"):
            em.line("pass")
        em.line("return 1")
    src = em.source(docstring="hello")
    assert src.count("import numpy as np") == 1
    assert "def run(tables):\n    for i in range(3):\n        pass\n    return 1" in src
    ast.parse(src)


def test_emitter_empty_block_gets_pass():
    em = Emitter()
    with em.block("def run(tables):"):
        pass
    ast.parse(em.source())


def test_emitter_fresh_names_are_unique_and_valid():
    em = Emitter()
    em.import_("import numpy as np")
    names = [em.fresh("scan"), em.fresh("scan"), em.fresh("sales.amount"),
             em.fresh("1st col"), em.fresh("np"), em.fresh("tables")]
    assert names[:2] == ["scan_1", "scan_2"]
    assert len(set(names)) == len(names)
    assert all(n.isidentifier() for n in names)
    assert "np" not in names and "tables" not in names


def test_docstring_with_backslashes_and_quotes_stays_valid():
    em = Emitter()
    em.line("x = 1")
    ast.parse(em.source(docstring='LIKE \'\\d\' and """quotes"""'))


# ------------------------------------------------------------------ generate()

@pytest.mark.parametrize("name", SAMPLE_IDS)
def test_generated_source_is_a_valid_self_contained_module(name):
    plan, _ = SAMPLE_PLANS[name]
    src = generate(plan, CATALOG)
    tree = ast.parse(src)
    funcs = [n for n in tree.body if isinstance(n, ast.FunctionDef)]
    assert [f.name for f in funcs] == ["run"]
    assert [a.arg for a in funcs[0].args.args] == ["tables"]
    assert isinstance(funcs[0].body[-1], ast.Return)
    assert ast.get_docstring(tree).startswith("Generated by qcompiler codegen")


def test_generated_module_runs_in_an_empty_namespace():
    """Self-contained: needs nothing from the caller except `tables`."""
    plan, _ = SAMPLE_PLANS["canonical_naive"]
    ns = {}
    exec(compile(generate(plan, CATALOG), "<t>", "exec"), ns)
    assert ns["run"](TABLES).to_rows() == [("ann", 9)]


@pytest.mark.parametrize("name", SAMPLE_IDS)
def test_passthrough_output_matches_interpreter(name):
    plan, ordered = SAMPLE_PLANS[name]
    expected = interpret(plan, TABLES)
    actual = compile_and_run(generate(plan, CATALOG, mode="passthrough"), TABLES)
    ok, why = compare_tables(expected, actual, ordered=ordered)
    assert ok, why


def test_emitted_plan_round_trips_to_an_equal_plan():
    plan, _ = SAMPLE_PLANS["canonical_naive"]
    ns = {}
    # `return interpret(root, tables)` -> `return (root, tables)`: hand back the rebuilt plan
    src = generate(plan, mode="passthrough").replace("return interpret(", "return (")
    exec(compile(src, "<t>", "exec"), ns)
    rebuilt, _ = ns["run"](TABLES)
    assert rebuilt == plan


def test_date_and_dtype_literals_are_emitted_as_code():
    plan = scan("sales", pred=op(">=", col("day"), lit("2024-03-01", DType.DATE)))
    src = generate(plan, CATALOG)
    assert "DType.DATE" in src
    assert compile_and_run(src, TABLES).column("id").to_pylist() == [3, 4, 5, 6]


# ------------------------------------------------------------------ runner errors

def test_syntax_error_reports_numbered_source_with_marker():
    src = "def run(tables):\n    x = (1 +\n    return x\n"
    with pytest.raises(GeneratedCodeError) as info:
        compile_and_run(src, {})
    msg = str(info.value)
    assert "SyntaxError" in msg
    assert "1 | def run(tables):" in msg
    assert info.value.lineno in (2, 3)
    assert f"--> {info.value.lineno} |" in msg


def test_runtime_error_points_at_the_generated_line():
    src = (
        "def run(tables):\n"
        "    a = 1\n"
        "    b = 0\n"
        "    c = a / b\n"
        "    return c\n"
    )
    with pytest.raises(GeneratedCodeError) as info:
        compile_and_run(src, {})
    assert info.value.lineno == 4
    assert "ZeroDivisionError" in str(info.value)
    assert "-->" in str(info.value) and "c = a / b" in str(info.value).split("-->")[1]
    assert isinstance(info.value.__cause__, ZeroDivisionError)


def test_error_raised_deep_inside_a_helper_still_reports_generated_line():
    src = generate(scan("missing_table"), mode="passthrough")
    with pytest.raises(GeneratedCodeError) as info:
        compile_and_run(src, TABLES)
    assert "missing_table" in str(info.value)
    assert "return interpret(" in src.splitlines()[info.value.lineno - 1]


def test_missing_input_table_in_compiled_code_points_at_its_line():
    class Cat:
        def schema(self, table):
            return [("x", DType.INT)]
    src = generate(scan("missing_table"), Cat())
    with pytest.raises(GeneratedCodeError) as info:
        compile_and_run(src, TABLES)
    assert "tables['missing_table']" in src.splitlines()[info.value.lineno - 1]


def test_module_without_run_or_wrong_return_type_is_rejected():
    with pytest.raises(GeneratedCodeError, match="no run"):
        compile_and_run("x = 1\n", {})
    with pytest.raises(GeneratedCodeError, match="expected runtime.Table"):
        compile_and_run("def run(tables):\n    return 42\n", {})


# ------------------------------------------------------------------ regressions

def test_is_null_renders_postfix():
    from runtime._compat import UnaryOp
    from runtime.expr_eval import render_expr
    assert render_expr(UnaryOp(op="IS NULL", operand=col("x"))) == "(x IS NULL)"
    assert render_expr(UnaryOp(op="is not null", operand=col("x"))) == "(x IS NOT NULL)"
    assert render_expr(UnaryOp(op="NOT", operand=col("x"))) == "(NOT x)"


def test_expected_row_counts_for_pruning_and_join_shapes():
    """Hand-computed sizes, so the parity tests above can't both be wrong together."""
    expect = {
        "pruned_group_by_without_aggs": 4,                 # US, EU, AP, NULL
        "pruned_scan_columns_cover_pushed_predicate": 3,   # amounts 30, 50, 60
        "pruned_scan_explicit_columns": 6,
        "join_true_inner": 12,                             # 3 customers x 4 orders
        "join_true_left_empty_right": 3,
        "join_false_inner": 0,
        "join_no_condition": 12,
        "filter_is_null_and_is_not_null": 5,               # all but id 4 (region AP, amount NULL)
    }
    for name, rows in expect.items():
        assert interpret(SAMPLE_PLANS[name][0], TABLES).num_rows == rows, name
