"""`generate(plan, catalog) -> str`: turn a plan into the source of a Python module.

Every generated module has the same outer shape:

    \"\"\"<header: mode + the plan it was generated from>\"\"\"
    <imports>

    def run(tables):
        ...
        return <Table>

Two modes:
  * compiled     — real numpy code, one commented section per operator (codegen/operators.py).
                   Every plan node has a compiler (Phase C3: Scan, Filter, Project;
                   Phase C4: Join, Aggregate, Sort, Limit).
  * passthrough  — the body rebuilds the plan as constructor calls and hands it to the
                   reference interpreter. Only used when asked for with mode="passthrough",
                   e.g. to measure what compilation buys in the benchmarks.
"""
from __future__ import annotations

import dataclasses
import datetime
import math

from codegen.emitter import Emitter
from codegen.exprgen import CodegenError
from codegen.operators import PlanCompiler, compilable
from runtime._compat import format_plan
from runtime.expr_eval import node_kind

_PLAN_KINDS = {"Scan", "Filter", "Project", "Join", "Aggregate", "Sort", "Limit"}


def generate(plan, catalog=None, mode: str = "auto") -> str:
    """Python source text for a module whose `run(tables)` executes `plan`.

    mode: "auto" (compile when possible), "compiled" (error if not possible),
          or "passthrough" (always interpret).
    """
    if mode not in ("auto", "compiled", "passthrough"):
        raise ValueError(f"unknown mode {mode!r}")
    if mode == "passthrough" or (mode == "auto" and not compilable(plan)):
        return _generate_passthrough(plan)
    if not compilable(plan):
        raise CodegenError("plan contains operators that are not compiled yet")
    return _generate_compiled(plan, catalog)


_HELPERS = ("as_table", "read_column", "build_table", "like", "take_or_null")


def _generate_compiled(plan, catalog) -> str:
    em = Emitter()
    compiler = PlanCompiler(em, catalog)
    with em.block("def run(tables):"):
        rel = compiler.compile(plan)
        compiler.finish(rel)

    body = em.body_text()
    em.import_("import numpy as np")
    em.import_("from runtime._compat import DType")
    used = [h for h in _HELPERS if f"{h}(" in body]
    em.import_(f"from runtime.vec import {', '.join(used)}")
    return em.source(docstring=_header(plan, mode="compiled (numpy)"))


def _generate_passthrough(plan) -> str:
    em = Emitter()
    builder = _PlanLiteral(em)

    with em.block("def run(tables):"):
        em.comment("Passthrough: rebuild the plan, then interpret it.")
        root = builder.emit(plan)
        em.blank()
        em.line(f"return interpret({root}, tables)")

    em.import_("from runtime import interpret")
    if builder.needs_datetime:
        em.import_("import datetime")
    em.import_(f"from runtime._compat import {', '.join(sorted(builder.used_classes))}")
    return em.source(docstring=_header(plan, mode="passthrough (interpreter)"))


def _header(plan, mode: str) -> str:
    tree = "\n".join(f"    {ln}" for ln in format_plan(plan).splitlines())
    return f"Generated by qcompiler codegen - mode: {mode}.\n\nPlan:\n{tree}\n"


class _PlanLiteral:
    """Emits Python statements that reconstruct an IR tree."""

    def __init__(self, em: Emitter):
        self.em = em
        self.used_classes: set[str] = set()
        self.needs_datetime = False

    def emit(self, node) -> str:
        """Emit assignments for `node`'s subtree; return the variable holding it."""
        kind = node_kind(node)
        child_vars = {}
        for f in _init_fields(node):
            value = getattr(node, f.name)
            if _is_plan(value):
                child_vars[f.name] = self.emit(value)

        args = []
        for f in _init_fields(node):
            value = getattr(node, f.name)
            if f.name in child_vars:
                args.append(f"{f.name}={child_vars[f.name]}")
            elif not _is_default(f, value):
                args.append(f"{f.name}={self.value(value)}")

        var = self.em.fresh(kind.lower())
        self.used_classes.add(kind)
        self.em.line(f"{var} = {kind}({', '.join(args)})")
        return var

    def value(self, v) -> str:
        """Python source for a field value (expressions, dtypes, lists, scalars)."""
        if v is None or isinstance(v, (bool, int, str)):
            return repr(v)
        if isinstance(v, float):
            return f"float({str(v)!r})" if (math.isnan(v) or math.isinf(v)) else repr(v)
        if isinstance(v, datetime.date):
            self.needs_datetime = True
            return f"datetime.date({v.year}, {v.month}, {v.day})"
        if type(v).__name__ == "DType":
            self.used_classes.add("DType")
            return f"DType.{v.name}"
        if isinstance(v, list):
            return "[" + ", ".join(self.value(x) for x in v) + "]"
        if isinstance(v, tuple):
            inner = ", ".join(self.value(x) for x in v)
            return f"({inner},)" if len(v) == 1 else f"({inner})"
        if dataclasses.is_dataclass(v):
            kind = node_kind(v)
            self.used_classes.add(kind)
            args = ", ".join(f"{f.name}={self.value(getattr(v, f.name))}"
                             for f in _init_fields(v)
                             if not _is_default(f, getattr(v, f.name)))
            return f"{kind}({args})"
        raise TypeError(f"cannot emit a literal for {type(v).__name__}: {v!r}")


def _init_fields(obj):
    return [f for f in dataclasses.fields(obj) if f.init]


def _is_default(f, value) -> bool:
    return f.default is not dataclasses.MISSING and value == f.default


def _is_plan(value) -> bool:
    if not dataclasses.is_dataclass(value):
        return False
    try:
        return node_kind(value) in _PLAN_KINDS
    except Exception:
        return False
